# Generated by Django 4.2.27 on 2026-01-12 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='status_type',
        ),
        migrations.AlterField(
            model_name='station',
            name='current_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='limit_value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
