# Generated by Django 4.2.27 on 2026-01-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmapp', '0002_remove_threshold_status_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threshold',
            options={},
        ),
        migrations.AlterField(
            model_name='threshold',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='alarmapp.station'),
        ),
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together={('station', 'limit_value')},
        ),
    ]
